### ISSUE TITLE
What happens if there are no valid votes?

### ISSUE THREAD

**Issue by robdockins** [cjerdonek/formal-rcv#11]
According to my understanding, if there are no properly-cast votes in an election, then no one is elected.  This follows from our specification, I believe, as no candidate will achieve a majority in any round because all vote counts are 0.

**Comment by cjerdonek** [comment]
> This follows from our specification, I believe, as no candidate will achieve a majority in any round because all vote counts are 0.

Two candidates tying for 50% in the final round is another example of no candidate achieving a majority in any round, but in that case I imagine you do want to elect a winner (to be selected by the tie-breaking method which, IIRC, is a variable input parameter).

So it seems another way to approach this case would be to handle it by resolving a successive series of ties: keep eliminating the last place person (and resolving the tie for last place in each case).  Then, when you are left with two candidates, resolve it in the same way as if there were a tie for 50% with positive numbers of votes.  Is there anything in the charter language to suggest that candidates with zero vote totals should be handled any differently from positive vote totals?

**Comment by jldodds** [comment]
What Rob means is that even if we do tiebreakers all the way down in a race with 0 votes, we reach a single candidate with 0 votes. Our definition of majority is:

``` coq
 Definition majority (e : election) (winner : candidate) :=
      forall total_votes winner_votes, 
        total_selected e total_votes ->
        first_choices winner e winner_votes ->
        (winner_votes * 2) > total_votes.
```

Which won't hold on a single candidate with 0 votes, when 2 \* the number of votes for the winner (0) is equal to the total number of selections made (0).

For two candidates each with one votes, we'll do a tiebreaker. The above definition does hold for any election with a single candidate with a non-zero number of votes, so we'll have a winner in that case.

**Comment by jldodds** [comment]
The SF statute only says that a candidate is elected if they receive a majority of votes. Our argument, and the one presented in our specification, is that 0 votes is not a a majority.

**Comment by cjerdonek** [comment]
Oh, I see.  When there are two candidates remaining, the tie-break isn't whom to elect at that point but whom to eliminate.  Yes, that interpretation seems reasonable.

**Comment by jldodds** [comment]
Is it reasonable wrt. what actually happens in elections? Or is there not precedent that you are aware of.

**Comment by cjerdonek** [comment]
This is _quite_ theoretical IMHO, at least in SF.  The smallest district in SF has tens of thousands of eligible voters.  They would all have to abstain or something similar.

**Comment by jldodds** [comment]
Great, I think that's a sufficient answer.
