### ISSUE TITLE
How do multi-seat elections work?

### ISSUE THREAD

**Issue by robdockins** [cjerdonek/formal-rcv#12]
Does SF have multi-seat elections?  If so how are they run? I don't see any provisions for that in the statute SF text; nor for Oakland or Berkely.

Minneapolis has explicit (and rather complicated!) procedures for multi-seat elections which are not at all what I would have expected.

**Comment by cjerdonek** [comment]
SF does have multi-seat elections (e.g. board of education), but they don't use RCV.  No jurisdictions in the SF Bay Area use RCV for multi-seat elections.
