### ISSUE TITLE
Pick/Find a library for implementation

### ISSUE THREAD

**Issue by jldodds** [cjerdonek/formal-rcv#6]
I've started outlining an implementation for SF ( #2 ). The issue that's quickly coming up is that we will eventually need two libraries to do this with any efficiency. The things that will almost certainly be helpful are a finite map and a sort.

Both of these exist in the Coq library with one problem: they use modules.

This is a problem with our lightweight approach, because modules can't interact with sections (so this is a problem for typeclasses too). So we can't make a mapping from candidates (which will likely be a variable in the section) to vote counts using the Coq standard library. It would be nice to not need to reimplement these, but I'm not sure that we should change our approach to modularity for their sake

**Comment by cjerdonek** [comment]
@jldodds So I can better understand, I have a couple questions:
1. When you say, "do this with any efficiency," do you mean efficiency in the sense of performance for the extracted code, or do you mean efficiency with respect simply to writing and maintaining the Coq code?  If the former, would an alternative approach be to define a specification in Coq for the function that we need to be efficient, and then to swap out the Coq implementation with an efficient OCaml or Haskell implementation in the world of the extracted code?  From an implementation perspective, it seems like this would be doable, though I don't know the implications for the formal verification / proof of correctness of the finished product.
2. Can you describe in more detail an example of a function that we need to be able to implement with efficiency in Coq, and why we need to be able to implement it (e.g. exactly where does it come up in the vote tabulation algorithm)?  Also, can you link to the existing Coq implementations you had in mind that use modules?

**Comment by jldodds** [comment]
Particularly, I'm thinking of vote tabulation, which will need to be efficient. We'll need a good finite map from candidates to vote counts. Essentially the algorithm will be

```
Fixpoint tabulate (next_ranks : list candidate) (counts : map candidate positive) : 
    map candidate positive :=
match next_ranks with
| h :: t => tabulate t (increment map candidate)
| nil => map
end.
```

 But you could be right, we might just want to swap our map out for something more efficient (OCaml hashtbl) in the extracted code. In that case, the Coq code can do the simplest thing (probably a list of pairs).

**Comment by cjerdonek** [comment]
Does Coq have arrays that you can access with a 0-based index?

**Comment by cjerdonek** [comment]
@jldodds Did you see the question above?

Also, in terms of performance, is the intent with the Coq implementation to generate a performant implementation (e.g. for "production" use), or simply to generate a provably correct implementation (e.g. for a reference implementation)?  I was thinking that the latter would make more sense -- especially initially -- because optimizing for performance can obscure the underlying concepts, etc.  Also, from what you were saying above, it seems like Coq might not be the right setting for that.

**Comment by jldodds** [comment]
There are no mutable structures in Coq, so the best we can hope to do for a get/set is log n in the size of the tree. 

Ideally we will end up with Coq code that can execute and will look as similar as possible to code that we extract that will be used in production. 

We do have some design choice here depending on what exactly we want to trust. If we feel confident that an ocaml data structure implements a map correctly, for example, we can use that for the extracted code, but this weakens the proofs slightly. 

In general you are correct, but in the case of libraries like maps and sorts, the interface is simple enough that if the proofs are already done, you shouldn't need to worry about the implementation at all. For now, I'm using the most naive solution possible, and it should be easy enough to swap out in the future.

**Comment by robdockins** [comment]
The naive data structures have acceptable performance on real election data (10s of seconds for SF mayoral election). I think we can close this for now.
